In [1]:
import tensorflow as tf
import pandas as pd

In [2]:
# 1. 과거 데이터 준비
url = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(url)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# 원핫인코딩
iris = pd.get_dummies(iris)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [4]:
iris.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [5]:
# 독립변수, 종속변수
independent = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]

In [6]:
# 2. 모델의 구조 만들기
x = tf.keras.layers.Input(shape=[4])
y = tf.keras.layers.Dense(3, activation='softmax')(x)
model = tf.keras.models.Model(x, y)
model.compile(loss='categorical_crossentropy')

In [7]:
# 3. 모델 학습하기
model.fit(independent, dependent, epochs=1000, verbose=0)
model.fit(independent, dependent, epochs=1)

Train on 150 samples
150/150 [==============================] - 0s 299us/sample - loss: 0.1530


In [8]:
# 4. 모델 이용하기
print(model.predict(independent[:5]))
print(dependent[:5])

[[9.9922132e-01 7.7868724e-04 4.2341270e-08]
 [9.9661899e-01 3.3806476e-03 3.8222686e-07]
 [9.9847549e-01 1.5243449e-03 1.6444100e-07]
 [9.9589348e-01 4.1057244e-03 8.0503969e-07]
 [9.9938190e-01 6.1809691e-04 3.5919715e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [9]:
# weights & bias 출력
print(model.get_weights())

[array([[ 1.2588664 ,  0.8085902 , -0.7120951 ],
       [ 2.6721995 , -0.08933138, -0.9451362 ],
       [-4.4530067 , -1.0918787 ,  0.70748436],
       [-3.9397962 , -1.1724256 ,  2.093133  ]], dtype=float32), array([ 1.5327022,  1.078294 , -1.1627173], dtype=float32)]
